//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIngenieria.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Voluntary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voluntary()
        {
            this.Activity = new HashSet<Activity>();
        }


        [Required]
        [Display(Name = "Identificación")]
        public string identification { get; set; }

        [Required]
        [Display(Name = "Nombre")]
        public string name { get; set; }

        [Required]
        [Display(Name = "Estado")]
        public bool state { get; set; }

        [Required]
        [Display(Name = "Apellidos")]
        public string last_name { get; set; }

        [Required]
        [Display(Name = "Identificación de fotos")]
        public int photo_id { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string email { get; set; }

        [Required]
        [Display(Name = "Dirección")]
        public string address { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Número de teléfono")]
        public string phone_number { get; set; }

        [Required]
        [Display(Name = "Descripción")]
        public string description { get; set; }

        [Required]
        [Display(Name = "Link a red social")]
        public string link { get; set; }
    
        public virtual Photo Photo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activity { get; set; }
    }
}
